### ISSUE TITLE
The dev branch blocks in the semaphore test case

### ISSUE THREAD

**Issue by skyfireitdiy** [skyfireitdiy/cocpp#23]
code:
```cpp
TEST(sync, condition_variable_notify_all)
{
    co_mutex              mu;
    co_condition_variable cond;
    int                   n = 100;

    co c1([&] {
        std::unique_lock lck(mu);
        cond.wait(lck);
        n -= 5;
    });
    co c2([&] {
        std::unique_lock lck(mu);
        cond.wait(lck);
        n -= 10;
    });
    n /= 2;
    this_co::sleep_for(1s);
    EXPECT_EQ(n, 50);
    cond.notify_all();
    c1.wait<void>();
    c2.wait<void>();
    EXPECT_EQ(n, 35);
}

```

info:

```plaintext
(gdb) i thread
  Id   Target Id                                Frame 
  1    Thread 0x7f6715397740 (LWP 65157) "test" std::allocator<std::_List_node<cocpp::co_ctx*> >::~allocator (this=0x7ffdf29da097, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/allocator.h:153
  2    Thread 0x7f6715396700 (LWP 65161) "test" futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55582d4bf560 <cocpp::co_singleton_static<cocpp::co_manager>::instance()::inst+1952>) at ../sysdeps/nptl/futex-internal.h:183
  3    Thread 0x7f6714b95700 (LWP 65162) "test" __lll_lock_wait (futex=futex@entry=0x55582e87c5d0, private=0) at lowlevellock.c:52
* 4    Thread 0x7f6713b93700 (LWP 65163) "test" futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55582e87c558) at ../sysdeps/nptl/futex-internal.h:183
  5    Thread 0x7f6712b91700 (LWP 65164) "test" futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55582e87ea78) at ../sysdeps/nptl/futex-internal.h:183
  6    Thread 0x7f671138e700 (LWP 65427) "test" futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55582e88309c) at ../sysdeps/nptl/futex-internal.h:183
  7    Thread 0x7f6703fff700 (LWP 65640) "test" futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55582e885e0c) at ../sysdeps/nptl/futex-internal.h:183
(gdb) bt
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55582e87c558) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55582e879fd0, cond=0x55582e87c530) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x55582e87c530, mutex=0x55582e879fd0) at pthread_cond_wait.c:638
#3  0x00007f67157c8e30 in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x000055582d375e49 in std::_V2::condition_variable_any::wait<std::unique_lock<std::recursive_mutex> > (this=0x55582e87c530, __lock=...) at /usr/include/c++/9/condition_variable:273
#5  0x000055582d383350 in cocpp::co_sleep_controller::sleep_if_need (this=0x55582e87c508) at source/cocpp/core/co_sleep_controller.cpp:17
#6  0x000055582d350f36 in cocpp::co_env::sleep_if_need<>() (this=0x55582e87bbf0) at include/cocpp/core/co_env.h:135
#7  0x000055582d343f6c in cocpp::co_env::start_schedule_routine__ (this=0x55582e87bbf0) at source/cocpp/core/co_env.cpp:338
#8  0x000055582d343ae7 in cocpp::co_env::<lambda()>::operator()(void) const (__closure=0x55582e87a048) at source/cocpp/core/co_env.cpp:295
#9  0x000055582d34d09f in std::__invoke_impl<void, cocpp::co_env::start_schedule()::<lambda()> >(std::__invoke_other, cocpp::co_env::<lambda()> &&) (__f=...) at /usr/include/c++/9/bits/invoke.h:60
#10 0x000055582d34cfc7 in std::__invoke<cocpp::co_env::start_schedule()::<lambda()> >(cocpp::co_env::<lambda()> &&) (__fn=...) at /usr/include/c++/9/bits/invoke.h:95
#11 0x000055582d34ceb6 in std::thread::_Invoker<std::tuple<cocpp::co_env::start_schedule()::<lambda()> > >::_M_invoke<0>(std::_Index_tuple<0>) (this=0x55582e87a048) at /usr/include/c++/9/thread:244
#12 0x000055582d34cd80 in std::thread::_Invoker<std::tuple<cocpp::co_env::start_schedule()::<lambda()> > >::operator()(void) (this=0x55582e87a048) at /usr/include/c++/9/thread:251
#13 0x000055582d34c8cc in std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::thread::_Invoker<std::tuple<cocpp::co_env::start_schedule()::<lambda()> > >, void>::operator()(void) const (this=0x7f6713b92df0) at /usr/include/c++/9/future:1362
#14 0x000055582d34c2d4 in std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>(), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::thread::_Invoker<std::tuple<cocpp::co_env::start_schedule()::<lambda()> > >, void> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/9/bits/std_function.h:286
#15 0x000055582d351b60 in std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>::operator()() const (this=0x7f6713b92df0) at /usr/include/c++/9/bits/std_function.h:688
#16 0x000055582d34f624 in std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) (this=0x55582e87a010, __f=0x7f6713b92df0, __did_set=0x7f6713b92d4f) at /usr/include/c++/9/future:561
#17 0x000055582d35ac11 in std::__invoke_impl<void, void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(std::__invoke_memfun_deref, void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&) (__f=@0x7f6713b92d90: (void (std::__future_base::_State_baseV2::*)(std::__future_base::_State_baseV2 * const, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()> *, bool *)) 0x55582d34f5d8 <std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)>, __t=@0x7f6713b92d60: 0x55582e87a010) at /usr/include/c++/9/bits/invoke.h:73
#18 0x000055582d3567c9 in std::__invoke<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&) (__fn=@0x7f6713b92d90: (void (std::__future_base::_State_baseV2::*)(std::__future_base::_State_baseV2 * const, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()> *, bool *)) 0x55582d34f5d8 <std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)>) at /usr/include/c++/9/bits/invoke.h:95
#19 0x000055582d351694 in std::call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(std::once_flag&, void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&)::{lambda()#1}::operator()() const (this=0x7f6713b92ce0) at /usr/include/c++/9/mutex:671
#20 0x000055582d3516e7 in std::call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(std::once_flag&, void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&)::{lambda()#2}::operator()() const (this=0x0) at /usr/include/c++/9/mutex:676
#21 0x000055582d351720 in std::call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(std::once_flag&, void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&)::{lambda()#2}::_FUN() () at /usr/include/c++/9/mutex:676
#22 0x00007f67158ec47f in __pthread_once_slow (once_control=0x55582e87a028, init_routine=0x7f67157cdc20 <__once_proxy>) at pthread_once.c:116
#23 0x000055582d3408dc in __gthread_once (__once=0x55582e87a028, __func=0x7f67157cdc20 <__once_proxy>) at /usr/include/x86_64-linux-gnu/c++/9/bits/gthr-default.h:700
#24 0x000055582d351824 in std::call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(std::once_flag&, void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&) (__once=..., __f=@0x7f6713b92d90: (void (std::__future_base::_State_baseV2::*)(std::__future_base::_State_baseV2 * const, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()> *, bool *)) 0x55582d34f5d8 <std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)>) at /usr/include/c++/9/mutex:683
#25 0x000055582d34f233 in std::__future_base::_State_baseV2::_M_set_result(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>, bool) (this=0x55582e87a010, __res=..., __ignore_failure=false) at /usr/include/c++/9/future:401
#26 0x000055582d34b73a in std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<cocpp::co_env::start_schedule()::<lambda()> > >, void>::<lambda()>::operator()(void) const (this=0x55582e87a010) at /usr/include/c++/9/future:1662
#27 0x000055582d34e106 in std::__invoke_impl<void, std::__future_base::_Async_state_impl<_BoundFn, _Res>::_Async_state_impl(_BoundFn&&) [with _BoundFn = std::thread::_Invoker<std::tuple<cocpp::co_env::start_schedule()::<lambda()> > >; _Res = void]::<lambda()> >(std::__invoke_other, std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<cocpp::co_env::start_schedule()::<lambda()> > >, void>::<lambda()> &&) (__f=...) at /usr/include/c++/9/bits/invoke.h:60
#28 0x000055582d34e04e in std::__invoke<std::__future_base::_Async_state_impl<_BoundFn, _Res>::_Async_state_impl(_BoundFn&&) [with _BoundFn = std::thread::_Invoker<std::tuple<cocpp::co_env::start_schedule()::<lambda()> > >; _Res = void]::<lambda()> >(std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<cocpp::co_env::start_schedule()::<lambda()> > >, void>::<lambda()> &&) (__fn=...) at /usr/include/c++/9/bits/invoke.h:95
#29 0x000055582d34deb4 in std::thread::_Invoker<std::tuple<std::__future_base::_Async_state_impl<_BoundFn, _Res>::_Async_state_impl(_BoundFn&&) [with _BoundFn = std::thread::_Invoker<std::tuple<cocpp::co_env::start_schedule()::<lambda()> > >; _Res = void]::<lambda()> > >::_M_invoke<0>(std::_Index_tuple<0>) (this=0x55582e87d018) at /usr/include/c++/9/thread:244
#30 0x000055582d34dd2e in std::thread::_Invoker<std::tuple<std::__future_base::_Async_state_impl<_BoundFn, _Res>::_Async_state_impl(_BoundFn&&) [with _BoundFn = std::thread::_Invoker<std::tuple<cocpp::co_env::start_schedule()::<lambda()> > >; _Res = void]::<lambda()> > >::operator()(void) (this=0x55582e87d018) at /usr/include/c++/9/thread:251
#31 0x000055582d34d3ae in std::thread::_State_impl<std::thread::_Invoker<std::tuple<std::__future_base::_Async_state_impl<_BoundFn, _Res>::_Async_state_impl(_BoundFn&&) [with _BoundFn = std::thread::_Invoker<std::tuple<cocpp::co_env::start_schedule()::<lambda()> > >; _Res = void]::<lambda()> > > >::_M_run(void) (this=0x55582e87d010) at /usr/include/c++/9/thread:195
#32 0x00007f67157cede4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#33 0x00007f67158e3609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#34 0x00007f67154be293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) frame 5
#5  0x000055582d383350 in cocpp::co_sleep_controller::sleep_if_need (this=0x55582e87c508) at source/cocpp/core/co_sleep_controller.cpp:17
17              cond__.wait(lock);
(gdb) p mu__
$7 = {<std::__recursive_mutex_base> = {_M_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 1, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 16 times>, "\001", '\000' <repeats 22 times>, __align = 0}}, <No data fields>}
```

This may be due to timing issues (currently using Sleep to control timing), so you can modify the use case to test it

Assignees: @skyfireitdiy
Labels: bug

**Comment by skyfireitdiy** [comment]
Recurrence means that the problem needs to call the test case about 100 times.

**Comment by skyfireitdiy** [comment]
I ran the test case 1000 times and it didn't happen. It should have been fixed and closed temporarily
